# This can be coreprotect, logblock, hawkeye or prism
# See the plugin documentation for more information on how this works
# Comment out this entry to disable block logging
logger: prism

# The rest of this file contains various message strings for you to customize.
# You can't leave any of these out! Make sure they're all here!
# You may also use various tokens in the messages, which will be listed in the comments below.
messages:
    # Tokens: {PERMISSION}, {NAME}
    replace_perm_lost: "&dCMP &5\u00BB&6 Replace mode disabled, your access to it has been &crevoked"
    # Tokens: {NAME}
    replace_mode_enable: "&dCMP &5\u00BB&6 Replace mode enabled, you are now replacing blocks"
    # Tokens: {NAME}
    replace_mode_disable: "&dCMP &5\u00BB&6 Replace mode disabled, you are no longer replacing blocks"

    # Tokens: {PERMISSION}, {NAME}
    range_replace_perm_lost: "&dCMP &5\u00BB&6 Range replace disabled, your access to it has been &crevoked"
    # Tokens: {NAME}
    range_replace_mode_enable: "&dCMP &5\u00BB&6 Range replace enabled, you are now replacing blocks at a distance"
    # Tokens: {NAME}
    range_replace_mode_disable: "&dCMP &5\u00BB&6 Range replace disabled, you are no longer replacing blocks at a distance"

    # Tokens: {NAME}
    command_player_only: "&dCMP &5\u00BB&6 This command can only be run by a player"
    # Tokens: {PERMISSION}, {NAME}
    command_replace_no_permission: "&dCMP &5\u00BB&6 You do not have permission to toggle replace mode"
    # Tokens: {PERMISSION}, {NAME}
    command_range_replace_no_permission: "&dCMP &5\u00BB&6 You do not have permission to toggle range replace mode"

# Don't change this! You'll break stuff!
version: 0.0.2