name: Painter
version: 0.0.3
description: Allows the painting of wool and clay, and the replacing of blocks

author: Gareth Coles

main: com.archivesmc.painter.Painter
database: false
softdepend: [LogBlock, CoreProtect, Prism, HawkEye, ArchBlock]

commands:
    painter:
        aliases: [paint, ptr, pt, p]
        description: "Toggle replacement (\"toggle\" or no arguments) and range replacement modes"
        usage: "/<command> [toggle|range]"

permissions:
    painter.*:
        children:
            painter.replace: true
            painter.replace.range: true
        description: All the Painter permissions
    painter.replace:
        description: Replace blocks by breaking them
    painter.replace.range:
        description: Replace blocks at range by left-clicking